### ISSUE TITLE
Add error-handling pop-up when a user tries to join two fields that do not match

### ISSUE THREAD

**Issue by LangsterGA** [WorldHealthOrganization/godata-extract-qgis-plugin#13]
For the case where a join is attempted (in optional section of dialog) with two fields that don't match, let the user know they don't match and so a join is not possible. Maybe even direct them to compare their join fields from the system field they are using (which is typically the 'locations' ID) and their GIS data attribute field, prior to attempting another join. This is a user error but it would be helpful to let them know it's not an application error.

**Comment by adm-gis** [comment]
resolved
