### ISSUE TITLE
Add 'contacts' output

### ISSUE THREAD

**Issue by LangsterGA** [WorldHealthOrganization/godata-extract-qgis-plugin#20]
Extract raw data for contacts and output to .csv. This should be the same information/fields returned with the SITREP toolkit raw contacts output file. I am updating this to remove these fields from the raw output: 'middleName' and 'visualId', as an added measure to maintain privacy of the data. 

[Contacts.csv](https://github.com/WorldHealthOrganization/godata-extract-qgis-plugin/files/10469313/Contacts.csv)

**Comment by LangsterGA** [comment]
This issue has been resolved by Adam.

**Comment by LangsterGA** [comment]
Hi Adam - your updates are working for me. I think we should also drop the fields: contact ID ('visualId') and middle name ('middleName') from the raw output csv.

**Comment by adm-gis** [comment]
Issue resolved with PR #27
